### ISSUE TITLE
Production-ready way to seed database

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#354] opened 2020-08-13 19:27 UTC
Current issues: The unknown problem with loading a lot of fixtures in staging has been bypassed, but not identified or really fixed.  State-specific files no longer have to be created as separate JSON files but are generated from generic sections and modified to include Section 0 answers. Mostly done in #683, but the fixture-loading problem addressed by https://github.com/18F/cms-carts-seds/pull/692 remains unresolved.

**Comment by timoballard** [comment] 2020-10-16 17:23
The issue with loading many fixtures appears to be caused by Jenkins terminating builds that run for more than 2 minutes. Will need to reach out to ops team for resolve confirming and resolving.

**Comment by mblevins-collabralink** [comment] 2020-10-17 16:11
I opened a task ticket for the DevOps team with high priority. They should get to it Monday, but I'll drop in their standup and make sure it gets raised.

**Comment by timoballard** [comment] 2020-10-21 17:23
Split out the portion of this ticket that deals with establishing a canonical source of truth for JSON structures as #863.

Marking this as closed after fixing fixture loading issue in #855

**Closed by timoballard** 2020-10-21 17:23 UTC
Labels: Rollover, database
