### ISSUE TITLE
Checkboxes with conditional logic tied to them

### ISSUE THREAD

**Issue by andrewadcock** [18F/cms-carts-seds#578] opened 2020-09-14 19:45 UTC
Checkboxes are not allowing for dependent children by reference. 

See section 3h, part 2, question 4 (http://localhost:81/sections/2020/03/h?dev=dev-ak) for an example.

This is likely due to the return type of checkboxes being an array as opposed to a string (like radios).

**Comment by cjhskippy** [comment] 2020-09-14 23:31
Related to (duplicate of?) #567

**Closed** 2020-09-26 19:36 UTC
